src/Entity/User.php
<?php
// src/Entity/User.php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="fos_user")
 */
class User extends BaseUser
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Article", mappedBy="user")
     */
    private $article;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $background;

    public function __construct()
    {
        parent::__construct();
        $this->article = new ArrayCollection();
        // your own logic
    }

    /**
     * @return Collection|Article[]
     */
    public function getArticle(): Collection
    {
        return $this->article;
    }

    public function addArticle(Article $article): self
    {
        if (!$this->article->contains($article)) {
            $this->article[] = $article;
            $article->setUser($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): self
    {
        if ($this->article->contains($article)) {
            $this->article->removeElement($article);
            // set the owning side to null (unless already changed)
            if ($article->getUser() === $this) {
                $article->setUser(null);
            }
        }

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(?string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(?string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getBackground(): ?string
    {
        return $this->background;
    }

    public function setBackground(?string $background): self
    {
        $this->background = $background;

        return $this;
    }
}

templates/bases/bases-FOS.html.twig
<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        Administration
    </title>
{#    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">#}

    <link rel="stylesheet" href="{{ asset('assets/bootstrap-4.3.1/dist/css/bootstrap.css') }}">
    <script
            src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{ asset('assets/css/styles.css') }}">
</head>
<body>
<main class="container-fluid admin-base-main">
    <div class="row admin-home-row">
        <div class="col-2 admin-base-container-menu">
            <div class="base-menu-box">
            </div>
        </div>
        <div class="col-10 admin-base-content">
            <h1 class="admin-h1">ID Bois</h1>
            {% block content %}
            {% endblock %}
        </div>
    </div>
</main>



{#<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>#}
{#<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>#}

<script src="{{ asset('assets/bootstrap-4.3.1/dist/js/bootstrap.js') }}"></script>

<script src="{{ asset('assets/js/script.js') }}"></script>

</body>
</html>

templates/bases/bases-admin.html.twig
<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        Administration
    </title>
{#    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">#}

    <link rel="stylesheet" href="{{ asset('assets/bootstrap-4.3.1/dist/css/bootstrap.css') }}">
    <script
            src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{ asset('assets/css/styles.css') }}">
</head>
<body>
<main class="container-fluid admin-base-main">
    <div class="row admin-home-row">
        <div class="col-2 admin-base-container-menu">
            <div class="base-menu-box">
            <a href="{{ path('fos_user_security_logout') }}"><button type="button" class="btn btn-secondary">Déconnexion</button></a>
                <nav class="base-menu">
                    <ul class="d-flex flex-column justify-content-around align-items-center">
                        <li><a href="{{ path('admin_home') }}" class="{{ app.request.get('_route') == 'home' ?'active' }}">Accueil</a></li>
                        <li><a href="{{ path('admin_gallery') }}" class="{{ 'gallery' in app.request.get('_route')
                            ?'active'
                            }}">Galerie</a></li>
                        <li><a href="{{ path('admin_ecolo') }}" class="{{ app.request.get('_route') == 'ecolo'?'active'
                            }}">Écolo</a></li>
                        <li><a href="{{ path('admin_profile') }}" class="{{ app.request.get('_route') ==
                            'contact'?'active'
                            }}">Présentation</a></li>
                    </ul>
                </nav>
            </div>
        </div>
        <div class="col-10 admin-base-content">
            <h1 class="admin-h1">ID Bois</h1>
            {% block content %}
            {% endblock %}
        </div>
    </div>
</main>



{#<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>#}
{#<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>#}

<script src="{{ asset('assets/bootstrap-4.3.1/dist/js/bootstrap.js') }}"></script>

<script src="{{ asset('assets/js/script.js') }}"></script>

</body>
</html>

templates/bases/bases.html.twig
<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link rel="icon" href="{{ asset('assets/img/logo.png') }}" />
    <meta name="robots" content="index,follow">
    <meta name="description" content="Iandy DOMENICHINI, menuisier ebeniste">
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@300;400;500;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script
            src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{ asset('assets/css/styles.css') }}">
</head>
<body>
    <main class="container-fluid base-main">
        <div class="d-block d-lg-none base-burger-box" onclick="showHiddenMenu();">
            <img class="img-fluid" src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Hamburger_icon.svg/1200px-Hamburger_icon.svg.png" alt="">
        </div>
        <div class="col-12 base-hidden-menu">
            <h1 class="base-hidden-h1">ID BOIS</h1>
            <span class="base-hidden-close" onclick="closeHiddenMenu()">X</span>
            <div class="cln"></div>
            <nav>
                <ul>
                    <li><a href="{{ path('home') }}">Accueil</a></li>
                    <li><a href="{{ path('gallery_home') }}">Galerie</a></li>
                    <li><a href="{{ path('ecolo') }}">Écolo</a></li>
                    <li><a href="{{ path('contact') }}">Contact</a></li>
                    <li><a href="https://www.etsy.com/fr/shop/IDbois91" target="_blank">Etsy</a></li>
                    <li class="base-networks-link">
                        <a href="https://www.instagram.com/id.bois/" class="base-networks"
                           target="_blank">
                            <img width="50px" height="auto" src="{{ asset('assets/icons/instagram.png') }}"
                                 alt="https://www.instagram.com/id.bois/">
                        </a>
                        <a href="https://www.facebook.com/idbois91/" class="base-networks"
                           target="_blank">
                            <img width="50px" height="auto" src="{{ asset('assets/icons/facebook.png') }}"
                                 alt="https://www.facebook.com/idbois91/">
                        </a>
                    </li>
                    <li><a href="{{ path('legal') }}">Mentions légales</a></li>
                </ul>
            </nav>
        </div>
        <div class="row home-row">
            <div class="d-none d-lg-block col-lg-2 base-container-menu">
                <div class="base-menu-box">
                    <nav class="base-menu">
                        <ul class="d-flex flex-column justify-content-around align-items-center">
                            <li><a href="{{ path('home') }}" class="{{ app.request.get('_route') == 'home' ?'active' }}">Accueil</a></li>
                            <li><a href="{{ path('gallery_home') }}" class="{{ 'gallery' in app.request.get
                                    ('_route') ?'active' }}">Galerie</a></li>
                            <li><a href="{{ path('ecolo') }}" class="{{ app.request.get('_route') == 'ecolo'
                                ?'active' }}">Écolo</a></li>
                            <li><a href="{{ path('contact') }}" class="{{ app.request.get('_route') == 'contact'
                                ?'active' }}">Contact</a></li>
                            <li><a href="https://www.etsy.com/fr/shop/IDbois91" target="_blank"
                                >Etsy</a></li>
                            <li class="base-networks-link">
                                <a href="https://www.instagram.com/id.bois/" class="base-networks"
                                target="_blank">
                                    <img width="50px" height="auto" src="{{ asset('assets/icons/instagram.png') }}"
                                         alt="https://www.instagram.com/id.bois/">
                                </a>
                                <a href="https://www.facebook.com/idbois91/" class="base-networks"
                                target="_blank">
                                    <img width="50px" height="auto" src="{{ asset('assets/icons/facebook.png') }}"
                                         alt="https://www.facebook.com/idbois91/">
                                </a>
                            </li>
                            <li><a href="{{ path('legal') }}" class="{{ app.request.get('_route') == 'legal'
                                ?'active-legal' }}"><span class="bases-legal">Mentions légales</span></a></li>
                        </ul>
                    </nav>
                </div>
            </div>
            <div class="col-12 col-lg-10 base-content">
                {% block content %}
                {% endblock %}
            </div>
            <div class="profile">
                <img class="img-fluid" src="{{ asset('assets/img') }}/{{ profile.picture }}" alt="Iandy DOMENICHINI photo de profil">
            </div>
            <div class="profile-content container-fluid">
                <div class="d-flex justify-content-end">
                    <span class="profile-content-close">X</span>
                </div>
                <div class="row">
                    <div class="col-12 col-lg-4">
                        <div class="col-4 col-lg-12 profile-img-box">
                            <img class="img-fluid" src="{{ asset('assets/img') }}/{{ profile.picture }}" alt="Iandy
                            DOMENICHINI photo
                             de profil">
                        </div>

                    </div>
                    <div class="col-12 col-lg-8">
                        <div class="cln"></div>
                        <div class="profile-text-box">
                            <h2>{{ profile.firstName }} {{ profile.lastName }}</h2>
                            <p>{{ profile.description|nl2br }}</p>
                        </div>

                    </div>
                </div>

            </div>
        </div>

        {% if cookie %}
            <div class="cookie container-fluid text-light">
                <div class="row align-items-center pt-4">
                    <div class="col-10">
                        <p>Ce site utilise des cookies pour améliorer votre expérience utilisateur.</p>
                    </div>
                    <div class="col-2">
                        <button class="btn btn-secondary cookie-btn">Ok</button>
                        <a href="{{ path('legal') }}" class="text-light pl-3">En savoir plus...</a>
                    </div>
                </div>
            </div>
        {% endif %}
    </main>


    <script src="{{ asset('assets/js/script.js') }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>