src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $main_picture;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="article")
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Picture", mappedBy="article")
     */
    private $picture;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Type", inversedBy="articles")
     */
    private $type;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\ProjectCategory", inversedBy="articles")
     */
    private $project_category;

    public function __construct()
    {
        $this->picture = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getMainPicture(): ?string
    {
        return $this->main_picture;
    }

    public function setMainPicture(?string $main_picture): self
    {
        $this->main_picture = $main_picture;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Picture[]
     */
    public function getPicture(): Collection
    {
        return $this->picture;
    }

    public function addPicture(Picture $picture): self
    {
        if (!$this->picture->contains($picture)) {
            $this->picture[] = $picture;
            $picture->setArticle($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): self
    {
        if ($this->picture->contains($picture)) {
            $this->picture->removeElement($picture);
            // set the owning side to null (unless already changed)
            if ($picture->getArticle() === $this) {
                $picture->setArticle(null);
            }
        }

        return $this;
    }

    public function getType(): ?Type
    {
        return $this->type;
    }

    public function setType(?Type $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getProjectCategory(): ?ProjectCategory
    {
        return $this->project_category;
    }

    public function setProjectCategory(?ProjectCategory $project_category): self
    {
        $this->project_category = $project_category;

        return $this;
    }
}

templates/contact.html.twig
{% extends 'bases/bases.html.twig' %}

{% block title %}
    Contact
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <section class="container contact-container">
            <h1 class="contact-h1">Contact</h1>
            {% for message in app.flashes('confirm') %}
                <div class="contact-confirm">
                    <p>{{ message }}</p>
                </div>
            {% endfor %}
            <div class="contact-vertical-line"></div>
            <form action="#" method="POST">
                <div class="form-group row align-items-center">
                    <div class="col-12 col-md-6 contact-label-box text-center text-md-right">
                        <label class="contact-label" for="name">Nom</label>
                    </div>
                    <div class="col-12 col-md-6 contact-input-box">
                        <input required type="text" name="name" placeholder="Votre nom" id="name" class="form-control
                        contact-input">
                    </div>
                </div>
                <div class="form-group row align-items-center">
                    <div class="col-12 col-md-6 contact-label-box text-center text-md-right">
                        <label class="contact-label" for="firstname">Prénom</label>
                    </div>
                    <div class="col-12 col-md-6 contact-input-box">
                        <input required type="text" name="firstname" placeholder="Votre Prénom" id="firstname"
                               class="form-control
                        contact-input">
                    </div>
                </div>
                <div class="form-group row align-items-center">
                    <div class="col-12 col-md-6 contact-label-box text-center text-md-right">
                        <label class="contact-label" for="phone">Numéro de téléphone</label>
                    </div>
                    <div class="col-12 col-md-6 contact-input-box">
                        <input required type="text" name="phone" placeholder="Votre numéro" id="phone"
                               class="form-control
                        contact-input">
                    </div>
                </div>
                <div class="form-group row align-items-center">
                    <div class="col-12 col-md-6 contact-label-box text-center text-md-right">
                        <label required class="contact-label" for="firstprojectname">Votre projet</label>
                    </div>
                    <div class="col-12 col-md-6 contact-input-box">
                        <textarea required class="contact-input" name="project" id="project" cols="30"
                                  rows="10"></textarea>
                    </div>
                </div>
                <div class="contact-submit-box">
                    <input type="submit" class="contact-submit" value="Envoyer" name="submit">
                </div>
            </form>
        <div class="container">
            <div class="contact-informations">
                <h2>Mes coordonnées</h2>
                <p>Téléphone <br/> {{ profile.phone }}</p>
                <p>Courriel <br/> {{ profile.email }}</p>
            </div>
        </div>
        </section>
    </div>
{% endblock %}

templates/ecolo.html.twig
{% extends 'bases/bases.html.twig' %}

{% block title %}
    Écolo
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="container ecolo-container">
            <h1 class="ecolo-h1">Écolo</h1>
            <div class="vertical-line vertical-line-ecolo"></div>
            <p class="ecolo-description">{{ description[0].description | nl2br  }}</p>
            {% set count = 0%}
            {% for article in articles %}
                <div class="row ecolo-row">
                    {% if count%2 == 0 %}
                        <div class="col-12 col-md-6 ecolo-text-right order-2 order-md-1">{{ article.description | nl2br  }}</div>
                        <div class="col-12 col-md-6 text-center order-1 order-md-2">
                            <div class="ecolo-img-box">
                                <img class="img-fluid" src="{{ asset('assets/img') }}/{{ article.mainPicture }}" alt="">
                            </div>
                        </div>
                    {% else %}
                        <div class="col-12 col-md-6 text-center order-1 order-md-1">
                            <div class="ecolo-img-box">
                                <img class="img-fluid" src="{{ asset('assets/img') }}/{{ article.mainPicture }}" alt="">
                            </div>
                        </div>
                        <div class="col-12 col-md-6 ecolo-text-left order-2 order-md-2">{{ article.description | nl2br  }}</div>
                    {% endif %}
                </div>
                {% set count = count +1 %}
            {% endfor %}


        </div>
    </div>
{% endblock %}

templates/gallery_categories.html.twig
{% extends 'bases/bases.html.twig' %}

{% block title %}
    Galerie
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="container gallery-container">
                <h1 class="gallery-h1">Galerie</h1>
                <div class="vertical-line"></div>
                <p class="gallery-p">Pour commencer, choisissez une catégorie : </p>
            <div class="row gallery-row">
                {% for category in categories %}
                    {% set column = 12/categories|length %}
                    {% if column < 3 %}
                        {% set column = 3 %}
                    {% endif %}
                    <div class="col-12 my-3 col-md-{{ column }} gallery-category-column">
                        <a href="{{ path('gallery_category',{'id':category.id}) }}">
                            <div class="gallery-category-box">
                                <h2>{{ category.name }}</h2>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/gallery_one_category.html.twig
{% extends 'bases/bases.html.twig' %}

{% block title %}
    Galerie
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="container gallery-container">
            <h1 class="gallery-h1">Galerie</h1>
            <div class="vertical-line"></div>
            <div class="row flex-wrap gallery-category-select">
                {% set column = 12/(categories|length + 1) %}
                {% for category in categories %}
                    {% if column < 3 %}
                        {% set column = 3 %}
                    {% endif %}
                    <div class="col-12 col-md-{{ column }} gallery-category-column">
                        <a href="{{ path('gallery_category',{'id':category.id}) }}">
                            <button class="gallery-category-box">{{ category.name }}</button>
                        </a>
                    </div>
                {% endfor %}
                <div class="col-12 col-md-{{ column }} gallery-category-column">
                    <a href="{{ path('gallery_category',{'id':'all'}) }}">
                        <button class="gallery-category-box">Toutes les catégories</button>
                    </a>
                </div>
            </div>
            <div class="row flex-wrap text-center">
                {% for project in projects %}
                    <div onclick="modalShow({{ project.id }});" class="col-12 col-md-3 gallery-project-column">
                            <div class="container gallery-project-box border border-light">
                                <div class="gallery-project-text">
                                    <h2>{{ project.title }}</h2>
                                </div>
                                <img class="img-fluid" src="{{ asset('assets/img') }}/{{ project.mainPicture }}"
                                     alt="{{ project.title }}">
                            </div>

                    </div>
                {% endfor %}

            </div>
        </div>
        <div class="gallery-category-modal-hidden"></div>
    </div>
{% endblock %}

templates/home.html.twig
{% extends 'bases/bases.html.twig' %}

{% block title %}
    ID BOIS
{% endblock %}

{% block content %}

    <div class="home-box">
        <div class="home-text-box">
            <p class="home-description">{{ description[0].description | nl2br }}</p>
        </div>
        <div>
            <a href="{{ path('contact') }}"><button class="home-button">{{ button[0].description | nl2br  }}</button></a>
        </div>
    </div>
{% endblock %}

templates/legal.html.twig
{% extends 'bases/bases.html.twig' %}

{% block title %}
    Mentions légales
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="container legal-container">
            <h1>Mentions légales</h1>

            <h2>Identification du site</h2>
            <p>Nom du site : ID-Bois</p>
            <p>URL complète du site : https://www.atelier-idbois.fr</p>

            <h2>Identification du propriétaire du site</h2>
            <p>Iandy DOMENICHINI</p>
            <p>Adresse : 2 avenue Granger 91210 - DRAVEIL</p>
            <p>Courriel : iandy.domenichini@hotmail.fr</p>
            <p>Réalisation du site web : Hery DOMENICHINI, développeur web du collectif <a
                        href="https://meliway.Fr">Meliway</a></p>
            <p>Responsable des publications : Iandy DOMENICHINI, propriétaire du site</p>

            <h2>Hébergement du site web</h2>
            <p>o2switch</p>
            <p>222-224 Boulevard Gustave Flaubert</p>
            <p>Capital de 100000€</p>
            <p>Siret : 510 909 807 00024</p>

            <h2>Activité</h2>
            <p>Numéro d'inscription au répertoir des métiers : 883 038 929 RM 91</p>

            <h2>Cookies</h2>
            <p>L'utilisation potentielle de cookies sur ce site a pour but d'améliorer l'expérience des utilisateurs.</p>

            <h2>Confidentialité</h2>
            <p>Les informations renseignées par l'utilisateur du site, notamment via le formulaire de contact, ne seront
                communiquées qu'au seul propriétaire du site.</p>
            <p>De même, les coordonnées fournies ne seront communiquées à une tierce partie.</p>

        </div>
    </div>


{% endblock %}

templates/project.html.twig
<span class="project-carousel-close" onclick="modalClose()">X</span>
<div class="cdn"></div>
<div id="carouselExampleControls" class="carousel slide project-carousel" data-ride="carousel">
    <div class="carousel-inner w-100 h-100">

        {% for picture in project.picture %}
            {% if loop.first %}
                <div class="carousel-item active w-100 h-100 ">
            {% else %}
                <div class="carousel-item w-100 h-100 ">
            {% endif %}

                <img class="d-block h-100 w-auto mx-auto img-fluid" src="{{ asset('assets/img') }}/{{ picture.name }}"
                     alt="image du projet {{ project.title }}">
            </div>
        {% endfor %}

    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon project-control" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon project-control" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
    <div class="project-description">
        <p>{{ project.description | nl2br  }}</p>
    </div>
</div>